# Generated by Django 4.2.11 on 2024-06-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_blog_description_alter_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='urrjwzi'),
        ),
    ]
