# Generated by Django 5.0.3 on 2024-03-27 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('schema_image', models.ImageField(blank=True, null=True, upload_to='Challenge/')),
                ('language', models.CharField(blank=True, max_length=150, null=True)),
                ('framework', models.CharField(blank=True, max_length=150, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('project', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('completed', models.BooleanField(default=False)),
                ('datesubmitted', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_task', to='Challenges.challenge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
