# Generated by Django 5.0.3 on 2024-03-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Challenges', '0002_challengeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeentry',
            name='database',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
